// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

public partial class ProductCategory
{
    [Key]
    public Guid Id { get; set; }

    public Guid? ParentCategoryId { get; set; }

    [Required]
    [StringLength(100)]
    public string CategoryName { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<SkinTypeRoutineStep> SkinTypeRoutineSteps { get; set; } = new List<SkinTypeRoutineStep>();
}