// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ProductId", Name = "IX_ProductItems_ProductId")]
public partial class ProductItem
{
    [Key]
    public Guid Id { get; set; }

    public int QuantityInStock { get; set; }

    [Required]
    [StringLength(500)]
    public string ImageUrl { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal MarketPrice { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal PurchasePrice { get; set; }

    public Guid ProductId { get; set; }

    [InverseProperty("ProductItem")]
    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    [InverseProperty("ProductItem")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [ForeignKey("ProductId")]
    [InverseProperty("ProductItems")]
    public virtual Product Product { get; set; }

    [InverseProperty("ProductItem")]
    public virtual ICollection<ProductConfiguration> ProductConfigurations { get; set; } = new List<ProductConfiguration>();
}