// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("QuizQuestionId", Name = "IX_QuizOptions_QuizQuestionId")]
public partial class QuizOption
{
    [Key]
    public Guid Id { get; set; }

    public Guid QuestionId { get; set; }

    [Required]
    [StringLength(255)]
    public string Value { get; set; }

    public int Score { get; set; }

    public Guid? QuizQuestionId { get; set; }

    public string CreatedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("QuizQuestionId")]
    [InverseProperty("QuizOptions")]
    public virtual QuizQuestion QuizQuestion { get; set; }
}