// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("QuizSetId", Name = "IX_QuizQuestions_QuizSetId")]
public partial class QuizQuestion
{
    [Key]
    public Guid Id { get; set; }

    public Guid SetId { get; set; }

    [Required]
    [StringLength(500)]
    public string Value { get; set; }

    public Guid? QuizSetId { get; set; }

    public string CreatedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("QuizQuestion")]
    public virtual ICollection<QuizOption> QuizOptions { get; set; } = new List<QuizOption>();

    [ForeignKey("QuizSetId")]
    [InverseProperty("QuizQuestions")]
    public virtual QuizSet QuizSet { get; set; }
}