// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("QuizSetId", Name = "IX_QuizResults_QuizSetId")]
[Index("SkinTypeId", Name = "IX_QuizResults_SkinTypeId")]
public partial class QuizResult
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Score { get; set; }

    public Guid SkinTypeId { get; set; }

    public Guid? QuizSetId { get; set; }

    public string CreatedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("QuizSetId")]
    [InverseProperty("QuizResults")]
    public virtual QuizSet QuizSet { get; set; }

    [ForeignKey("SkinTypeId")]
    [InverseProperty("QuizResults")]
    public virtual SkinType SkinType { get; set; }
}