// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("SkinTypeId", Name = "IX_SkinAnalysisResults_SkinTypeId")]
[Index("UserId", Name = "IX_SkinAnalysisResults_UserId")]
public partial class SkinAnalysisResult
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(1000)]
    public string ImageUrl { get; set; }

    public Guid UserId { get; set; }

    public Guid SkinTypeId { get; set; }

    public int AcneScore { get; set; }

    public int WrinkleScore { get; set; }

    public int DarkCircleScore { get; set; }

    public int DarkSpotScore { get; set; }

    public int HealthScore { get; set; }

    public int OilinessLevel { get; set; }

    public int DrynessLevel { get; set; }

    public int SensitivityLevel { get; set; }

    public string FullAnalysisJson { get; set; }

    public DateTimeOffset CreatedTime { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset LastUpdatedTime { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public string DeletedBy { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("SkinAnalysisResult")]
    public virtual ICollection<SkinAnalysisIssue> SkinAnalysisIssues { get; set; } = new List<SkinAnalysisIssue>();

    [InverseProperty("SkinAnalysisResult")]
    public virtual ICollection<SkinAnalysisRecommendation> SkinAnalysisRecommendations { get; set; } = new List<SkinAnalysisRecommendation>();

    [ForeignKey("SkinTypeId")]
    [InverseProperty("SkinAnalysisResults")]
    public virtual SkinType SkinType { get; set; }
}