// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("SkinAnalysisResultId", Name = "IX_SkinAnalysisIssues_SkinAnalysisResultId")]
public partial class SkinAnalysisIssue
{
    [Key]
    public Guid Id { get; set; }

    public Guid SkinAnalysisResultId { get; set; }

    [Required]
    [StringLength(100)]
    public string IssueName { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public int Severity { get; set; }

    [ForeignKey("SkinAnalysisResultId")]
    [InverseProperty("SkinAnalysisIssues")]
    public virtual SkinAnalysisResult SkinAnalysisResult { get; set; }
}