// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("CategoryId", Name = "IX_SkinTypeRoutineSteps_CategoryId")]
[Index("SkinTypeId", Name = "IX_SkinTypeRoutineSteps_SkinTypeId")]
public partial class SkinTypeRoutineStep
{
    [Key]
    public Guid Id { get; set; }

    public Guid SkinTypeId { get; set; }

    public Guid CategoryId { get; set; }

    [Required]
    [StringLength(255)]
    public string StepName { get; set; }

    [Required]
    public string Instruction { get; set; }

    public int Order { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("SkinTypeRoutineSteps")]
    public virtual ProductCategory Category { get; set; }

    [ForeignKey("SkinTypeId")]
    [InverseProperty("SkinTypeRoutineSteps")]
    public virtual SkinType SkinType { get; set; }
}