// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

public partial class SkinType
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    [Required]
    [StringLength(1000)]
    public string Description { get; set; }

    [InverseProperty("SkinType")]
    public virtual ICollection<ProductForSkinType> ProductForSkinTypes { get; set; } = new List<ProductForSkinType>();

    [InverseProperty("SkinType")]
    public virtual ICollection<QuizResult> QuizResults { get; set; } = new List<QuizResult>();

    [InverseProperty("SkinType")]
    public virtual ICollection<SkinAnalysisResult> SkinAnalysisResults { get; set; } = new List<SkinAnalysisResult>();

    [InverseProperty("SkinType")]
    public virtual ICollection<SkinTypeRoutineStep> SkinTypeRoutineSteps { get; set; } = new List<SkinTypeRoutineStep>();
}