// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ProductId", Name = "IX_SkinAnalysisRecommendations_ProductId")]
[Index("SkinAnalysisResultId", Name = "IX_SkinAnalysisRecommendations_SkinAnalysisResultId")]
public partial class SkinAnalysisRecommendation
{
    [Key]
    public Guid Id { get; set; }

    public Guid SkinAnalysisResultId { get; set; }

    public Guid ProductId { get; set; }

    [StringLength(1000)]
    public string RecommendationReason { get; set; }

    public int PriorityScore { get; set; }

    [ForeignKey("SkinAnalysisResultId")]
    [InverseProperty("SkinAnalysisRecommendations")]
    public virtual SkinAnalysisResult SkinAnalysisResult { get; set; }
}