// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ProductItemId", Name = "IX_CartItems_ProductItemId")]
[Index("UserId", Name = "IX_CartItems_UserId")]
public partial class CartItem
{
    [Key]
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid ProductItemId { get; set; }

    public int Quantity { get; set; }

    [ForeignKey("ProductItemId")]
    [InverseProperty("CartItems")]
    public virtual ProductItem ProductItem { get; set; }
}