// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("OrderId", Name = "IX_OrderDetails_OrderId")]
[Index("ProductItemId", Name = "IX_OrderDetails_ProductItemId")]
public partial class OrderDetail
{
    [Key]
    public Guid Id { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    public Guid ProductItemId { get; set; }

    public Guid OrderId { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderDetails")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductItemId")]
    [InverseProperty("OrderDetails")]
    public virtual ProductItem ProductItem { get; set; }
}